### ISSUE TITLE
Add ability to edit text

### ISSUE THREAD

**Issue by JesseRWeigel** [JesseRWeigel/voice-to-text-notes#18]
This should be done after the ability to save text locally has been added.

**Comment by ayrbox** [comment]
@JesseRWeigel when you say ability to save it locally do you mean in local storage? or save it to disk?

**Comment by JesseRWeigel** [comment]
Just local storage

**Comment by ayrbox** [comment]
Hey @JesseRWeigel  Could you assign this to me please? 

Also, I'm thinking to change UI. How to proceed that? Is it be OK to put the changes to this thread?

**Comment by JesseRWeigel** [comment]
Sounds good. We can make the ui a different issue, or keep it here. If we need to bring in a package to help I am familiar with MaterialUI. We can use that.

**Comment by ayrbox** [comment]
Hey @JesseRWeigel, I've got this PR this ☝️  does not exactly user localStorage yet.

If you want you can wait for localStorage pr before you merge this. 

Just a thought, we might be able to add `Save` button next to text box that will actually store in localStorage. When transcribe is active then it will append the transcripts on top of previously saved transcripts.
