### ISSUE TITLE
Create a stop transcription button

### ISSUE THREAD

**Issue by BekahHW** [JesseRWeigel/voice-to-text-notes#6]
After the user clicks the transcribe button, it gives permission to the microphone to listen and to transcribe. Currently, there's no way to stop the transcription.

In the `App.tsx` file, add a "Stop Transcription" button that stops transcription. You might consider using hooks to track the state of transcription

**Comment by ayrbox** [comment]
@BekahHW 
created a hook with transcribing state PR #16 .
All logic to interact with media recorder is now inside hook.
