### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by JesseRWeigel** [JesseRWeigel/voice-to-text-notes#8]
We should have some tests for this app. I am using cypress on another project. We don't have to use cypress, but it may provide some consistency across projects.

**Comment by shyambh** [comment]
Hi @JesseRWeigel , I can write a few cypress tests for the app.

**Comment by JesseRWeigel** [comment]
For now we just need testing set up and make sure the page loads properly. As we add features we will need more tests.

**Comment by shyambh** [comment]
Thanks. I'm on it. Will send out the PR soon.

**Comment by shyambh** [comment]
Hi @JesseRWeigel can this issue be closed now?

**Comment by JesseRWeigel** [comment]
Yes, sorry I forgot to close it.
